const menu = [
{
    Id: 1,
    title: "Buttermilk Pancakes",
    category: "Breakfast",
    prace: 15.99,
    image: "./img/item-1.jpg",
    description: "I'm baby woke milkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed.",
},
{
    Id: 2,
    title: "Diner Double",
    category: "Lunch",
    prace: 13.99,
    image: "./img/item-2.jpg",
    description: "Vaporware iphone mumnlecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing.",
},
{
    Id: 3,
    title: "Godzilla",
    category: "Shakes",
    prace: 6.99,
    image: "./img/item-3.jpg",
    description: "ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral",
},
{
    Id: 4,
    title: "Country Delight",
    category: "Breakfast",
    prace: 20.99,
    image: "./img/item-4.jpg",
    description: "Shabby chic keffiyeh neutra snackwave pork belly shoreditch.Prism austin mlkshk truffaut.",
},
{
    Id: 5,
    title: "Egg Attack",
    category: "Lunch",
    prace: 22.99,
    image: "./img/item-5.jpg",
    description: "Franzen vegan pabst bicycle rights kickstater pinterest meditation farm-to-table 90's pop-up",
},
{
    Id: 6,
    title: "Oreo Dream",
    category: "Shakes",
    prace: 18.99,
    image: "./img/item-6.jpg",
    description: "Portland chicharrones ethical edison, palo santo craft beer chia heirloom iphone everyday",
},
{
    Id: 7,
    title: "Bacon Overflow",
    category: "Breakfast",
    prace: 8.99,
    image: "./img/item-7.jpg",
    description: "Carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird",
},
{
    Id: 8,
    title: "American Classic",
    category: "Lunch",
    prace: 12.99,
    image: "./img/item-8.jpg",
    description: "On it tumblr kickstarter thundercast migas everyday carry squid palo santo leggings. Food truck truffaut",
},
{
    Id: 9,
    title: "Quarantine Buddy",
    category: "Shakes",
    prace: 16.99,
    image: "./img/item-9.jpg",
    description: "Skateboard fam synth authentic semiotics. Live-edge lyft af, edison buld yuccie crucifix microdosing",
},
{
    Id: 10,
    title: "Starck Dinner",
    category: "Dinner",
    prace: 39.99,
    image: "./img/item-10.jpg",
    description: "Skateboard fam synth authentic semiotics. Live-edge lyft af, edison buld yuccie crucifix microdosing",
},
]

